AllCops:
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/**/*'
    - 'spec/*'
    - 'node_modules/**/*'
    - 'public/**/*'
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 200
